In [5]:
import pandas as pd

# Cargar el archivo parquet
df1 = pd.read_parquet('business_fl.parquet')

# Mostrar el head del dataframe
df1.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours,rounded_latitude,rounded_longitude,normalized_name
0,0bPLkL0QhhPO5kt1_EXmNQ,Zio's Italian Market,2575 E Bay Dr,Largo,FL,33771,27.916116,-82.760461,4.5,100,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Food, Delis, Italian, Bakeries, Restaurants","{'Friday': '10:0-20:0', 'Monday': '10:0-18:0',...",27.92,-82.76,"Local en (27.7121935, -82.2979132)"
1,cVBxfMC4lp3DnocjYA3FHQ,Paws The Cat Cafe,10588 109 Street,Edmonton,FL,<NA>,53.549633,-113.508780,5.0,20,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Coffee & tea, Cafes, Pets, Restaurants, Pet ad...","{'Friday': '10:0-20:0', 'Monday': '0:0-0:0', '...",53.55,-113.51,"Local en (27.772925866666668, -82.67718393333334)"
2,seKihQKpGGnCeLuELRQPSQ,Twin Peaks,6880 E 82nd St,Indianapolis,FL,46250,39.906295,-86.047463,3.5,257,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Sports bars, American (new), American (traditi...","{'Friday': '11:0-19:0', 'Monday': '0:0-0:0', '...",39.91,-86.05,"Local en (27.7679350194, -82.3935427381)"
3,L_TT0BFmFwORAMaA83K54A,Village Tap Room,838 Broad Ripple Ave,Indianapolis,FL,46220,39.869911,-86.143577,2.5,23,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Gastropubs, Cocktail bars, Beer bar, Bars, Res...",None,39.87,-86.14,"Local en (27.782413, -82.781687)"
4,ppFCk9aQkM338Rgwpl2F5A,Wawa,3604 Chestnut St,Philadelphia,FL,19104,39.954573,-75.194894,3.0,56,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Restaurants, Automotive, Delis, Gas stations, ...","{'Friday': '0:0-0:0', 'Monday': '0:0-0:0', 'Sa...",39.95,-75.19,"Local en (27.7937428, -82.6465296)"

In [56]:
print("Número de filas en filtered_result:", len(df1))

Número de filas en filtered_result: 11997

In [70]:
print(df1.columns)

Index(['business_id', 'name', 'address', 'city', 'state', 'postal_code',
       'latitude', 'longitude', 'stars', 'review_count', 'is_open',
       'attributes', 'categories', 'hours', 'rounded_latitude',
       'rounded_longitude', 'normalized_name', 'distance_to_ref'],
      dtype='object')

In [6]:
import pandas as pd

# Cargar el archivo parquet
df2 = pd.read_parquet('Joined_Restaurant_Bars_Florida_Google.parquet')

# Mostrar el head del dataframe
df2.head()

,name_x,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,...,state,relative_results,url,user_id,name_y,time,rating,text,pics,resp
0,Gormley's on the river | Modern cuisine in his...,Gormley's on the river | Modern cuisine in his...,0x8894b5a7a7909725:0xe4687299fd288188,None,29.726949,-84.981535,"[Modern French restaurant, Restaurant]",4.3,17,None,...,Permanently closed,"[0x8894b5a649e1f5cb:0xe5ef826dc2f3842f, 0x8894...",https://www.google.com/maps/place//data=!4m2!3...,1.130683e+20,Edwin Ashurst,1537195868022,5,The salads were lackluster though with well wr...,None,None
1,Gormley's on the river | Modern cuisine in his...,Gormley's on the river | Modern cuisine in his...,0x8894b5a7a7909725:0xe4687299fd288188,None,29.726949,-84.981535,"[Modern French restaurant, Restaurant]",4.3,17,None,...,Permanently closed,"[0x8894b5a649e1f5cb:0xe5ef826dc2f3842f, 0x8894...",https://www.google.com/maps/place//data=!4m2!3...,1.059416e+20,Douglas Gummere,1537402367631,1,"Love this place. Great little restaurant, with...",None,None
2,Gormley's on the river | Modern cuisine in his...,Gormley's on the river | Modern cuisine in his...,0x8894b5a7a7909725:0xe4687299fd288188,None,29.726949,-84.981535,"[Modern French restaurant, Restaurant]",4.3,17,None,...,Permanently closed,"[0x8894b5a649e1f5cb:0xe5ef826dc2f3842f, 0x8894...",https://www.google.com/maps/place//data=!4m2!3...,1.098577e+20,David Powell,1534936396392,5,A classy restaurant to match the charm of the ...,None,None
3,Gormley's on the river | Modern cuisine in his...,Gormley's on the river | Modern cuisine in his...,0x8894b5a7a7909725:0xe4687299fd288188,None,29.726949,-84.981535,"[Modern French restaurant, Restaurant]",4.3,17,None,...,Permanently closed,"[0x8894b5a649e1f5cb:0xe5ef826dc2f3842f, 0x8894...",https://www.google.com/maps/place//data=!4m2!3...,1.147377e+20,Hillary Hutchins,1555464332274,5,Great atmosphere and good food,None,None
4,Gormley's on the river | Modern cuisine in his...,Gormley's on the river | Modern cuisine in his...,0x8894b5a7a7909725:0xe4687299fd288188,None,29.726949,-84.981535,"[Modern French restaurant, Restaurant]",4.3,17,None,...,Permanently closed,"[0x8894b5a649e1f5cb:0xe5ef826dc2f3842f, 0x8894...",https://www.google.com/maps/place//data=!4m2!3...,1.089870e+20,Ajay patel,1558392170993,5,Good food,None,None

In [58]:
print("Número de filas en filtered_result:", len(df2))

Número de filas en filtered_result: 601786

In [71]:
print(df2.columns)

Index(['name_x', 'address', 'gmap_id', 'description', 'latitude', 'longitude',
       'category', 'avg_rating', 'num_of_reviews', 'price', 'hours', 'MISC',
       'state', 'relative_results', 'url', 'user_id', 'name_y', 'time',
       'rating', 'text', 'pics', 'resp', 'distance_to_ref'],
      dtype='object')

In [7]:
from geopy.distance import geodesic
import pandas as pd
from tqdm import tqdm

tqdm.pandas()


# Función para encontrar el negocio más cercano en df2 para cada entrada en df1
def find_closest_business(row, df2):
    min_distance = float('inf')
    closest_business = None
    for _, business in df2.iterrows():
        distance = geodesic((row['latitude'], row['longitude']), (business['latitude'], business['longitude'])).miles
        if distance < min_distance:
            min_distance = distance
            closest_business = business
    return closest_business['name'], min_distance

# Aplicar la función a cada fila en df1
df1[['closest_business', 'distance']] = df1.progress_apply(lambda row: find_closest_business(row, df2), axis=1, result_type='expand')

# Muestra el Dataframe actualizado
print(df1.head())

  0%|          | 1/11997 [02:27<492:40:44, 147.85s/it]

KeyError: 'name'

In [10]:
from geopy.distance import geodesic
import math 
import numpy as np

def haversine_distance(lat1, lon1, lat2, lon2):
    # Convertir latitudes y longitudes a radianes (usando math.radians en vez de geopy.degrees)
    lat1_rad = math.radians(lat1)
    lon1_rad = math.radians(lon1)
    lat2_rad = math.radians(lat2)
    lon2_rad = math.radians(lon2)

    # Calcule el radio de la Tierra
    earth_radius = 6371  # km (or 3959 miles)

    # Aplicar la fórmula de Haversine
    delta_lat = lat2_rad - lat1_rad
    delta_lon = lon2_rad - lon1_rad
    a = np.sin(delta_lat / 2) ** 2 + np.cos(lat1_rad) * np.cos(lat2_rad) * np.sin(delta_lon / 2) ** 2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))

    # Calcular la distancia
    distance = earth_radius * c

    return distance

In [11]:
# Calcular la latitud y longitud promedio
avg_lat = (df1['latitude'].mean() + df2['latitude'].mean()) / 2
avg_lon = (df1['longitude'].mean() + df2['longitude'].mean()) / 2

# Agregar columnas de distancia a los DataFrames
df1['distance_to_ref'] = df1.apply(lambda row: haversine_distance(row['latitude'], row['longitude'], avg_lat, avg_lon), axis=1)
df2['distance_to_ref'] = df2.apply(lambda row: haversine_distance(row['latitude'], row['longitude'], avg_lat, avg_lon), axis=1)

In [12]:
# Unir los DataFrames basado en la distancia mínima
merged_df = df1.merge(df2, on='distance_to_ref', how='inner', sort=False)

In [13]:
merged_df.head()

,business_id,name,address_x,city,state_x,postal_code,latitude_x,longitude_x,stars,review_count,...,state_y,relative_results,url,user_id,name_y,time,rating,text,pics,resp
0,OD6RYPrU2QTyTg6_4GYpbA,Brandon Pizzeria,140 N Parsons Ave,Brandon,FL,33510,27.939206,-82.286084,3.5,147,...,Open ⋅ Closes 9PM,None,https://www.google.com/maps/place//data=!4m2!3...,1.091736e+20,Jesse Nieves,1610802361016,5,The restaurant is open for dining and provides...,[{'url': ['https://lh5.googleusercontent.com/p...,{'text': 'Jesse thanks so much for your suppor...
1,OD6RYPrU2QTyTg6_4GYpbA,Brandon Pizzeria,140 N Parsons Ave,Brandon,FL,33510,27.939206,-82.286084,3.5,147,...,Open ⋅ Closes 9PM,None,https://www.google.com/maps/place//data=!4m2!3...,1.048419e+20,Brandon Rivera,1615592749399,5,Went here bc we wanted pizza and thought it wa...,[{'url': ['https://lh5.googleusercontent.com/p...,{'text': 'Brandon thanks so much for the great...
2,OD6RYPrU2QTyTg6_4GYpbA,Brandon Pizzeria,140 N Parsons Ave,Brandon,FL,33510,27.939206,-82.286084,3.5,147,...,Open ⋅ Closes 9PM,None,https://www.google.com/maps/place//data=!4m2!3...,1.088751e+20,Dirty McFergie,1618178402121,5,Such a variety of food and every item I have t...,None,{'text': 'Thank you for the wonderful review! ...
3,OD6RYPrU2QTyTg6_4GYpbA,Brandon Pizzeria,140 N Parsons Ave,Brandon,FL,33510,27.939206,-82.286084,3.5,147,...,Open ⋅ Closes 9PM,None,https://www.google.com/maps/place//data=!4m2!3...,1.154607e+20,Erik Chambers,1615426136118,5,"Food is fantastic, pizza had great flavor and ...",None,{'text': 'Thanks so much for the great review!...
4,OD6RYPrU2QTyTg6_4GYpbA,Brandon Pizzeria,140 N Parsons Ave,Brandon,FL,33510,27.939206,-82.286084,3.5,147,...,Open ⋅ Closes 9PM,None,https://www.google.com/maps/place//data=!4m2!3...,1.028419e+20,Benjamin Kent,1615943551381,5,What a fresh menu! Owners hand craft spicy che...,None,{'text': 'Ben thanks so much for the great rev...

In [15]:
print(merged_df['name'])

0      Brandon Pizzeria
1      Brandon Pizzeria
2      Brandon Pizzeria
3      Brandon Pizzeria
4      Brandon Pizzeria
             ...
817     Stone Soup Cafe
818     Stone Soup Cafe
819     Stone Soup Cafe
820     Stone Soup Cafe
821     Stone Soup Cafe
Name: name, Length: 822, dtype: object

In [16]:
merged_df2 = df2.merge(df1, on='distance_to_ref', how='inner', sort=False)

In [17]:
merged_df2.head()

,name_x,address_x,gmap_id,description,latitude_x,longitude_x,category,avg_rating,num_of_reviews,price,...,longitude_y,stars,review_count,is_open,attributes,categories,hours_y,rounded_latitude,rounded_longitude,normalized_name
0,Hawk n Hog Brandon,"Hawk n Hog Brandon, 140 N Parsons Ave, Brandon...",0x88c2cda39abc70df:0xc66aed3701bce637,None,27.939206,-82.286084,[Restaurant],4.3,68,$$,...,-82.286084,3.5,147,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Salad, Pizza, Restaurants, Italian","{'Friday': '11:0-23:0', 'Monday': '11:0-22:0',...",27.94,-82.29,None
1,Hawk n Hog Brandon,"Hawk n Hog Brandon, 140 N Parsons Ave, Brandon...",0x88c2cda39abc70df:0xc66aed3701bce637,None,27.939206,-82.286084,[Restaurant],4.3,68,$$,...,-82.286084,3.5,147,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Salad, Pizza, Restaurants, Italian","{'Friday': '11:0-23:0', 'Monday': '11:0-22:0',...",27.94,-82.29,None
2,Hawk n Hog Brandon,"Hawk n Hog Brandon, 140 N Parsons Ave, Brandon...",0x88c2cda39abc70df:0xc66aed3701bce637,None,27.939206,-82.286084,[Restaurant],4.3,68,$$,...,-82.286084,3.5,147,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Salad, Pizza, Restaurants, Italian","{'Friday': '11:0-23:0', 'Monday': '11:0-22:0',...",27.94,-82.29,None
3,Hawk n Hog Brandon,"Hawk n Hog Brandon, 140 N Parsons Ave, Brandon...",0x88c2cda39abc70df:0xc66aed3701bce637,None,27.939206,-82.286084,[Restaurant],4.3,68,$$,...,-82.286084,3.5,147,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Salad, Pizza, Restaurants, Italian","{'Friday': '11:0-23:0', 'Monday': '11:0-22:0',...",27.94,-82.29,None
4,Hawk n Hog Brandon,"Hawk n Hog Brandon, 140 N Parsons Ave, Brandon...",0x88c2cda39abc70df:0xc66aed3701bce637,None,27.939206,-82.286084,[Restaurant],4.3,68,$$,...,-82.286084,3.5,147,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Salad, Pizza, Restaurants, Italian","{'Friday': '11:0-23:0', 'Monday': '11:0-22:0',...",27.94,-82.29,None

In [18]:
print(merged_df2['name'])

0      Brandon Pizzeria
1      Brandon Pizzeria
2      Brandon Pizzeria
3      Brandon Pizzeria
4      Brandon Pizzeria
             ...
817     Stone Soup Cafe
818     Stone Soup Cafe
819     Stone Soup Cafe
820     Stone Soup Cafe
821     Stone Soup Cafe
Name: name, Length: 822, dtype: object

In [23]:
from geopy.distance import geodesic  # Use la función de distancia geodésica

def haversine_distance(lat1, lon1, lat2, lon2):
    # Convierta latitudes y longitudes a radianes (usando matemáticas)
    lat1_rad = math.radians(lat1)
    lon1_rad = math.radians(lon1)
    lat2_rad = math.radians(lat2)
    lon2_rad = math.radians(lon2)

    # Calcule el radio de la Tierra
    earth_radius = 6371  # km (or 3959 miles)

    #Aplicar la fórmula de Haversine
    delta_lat = lat2_rad - lat1_rad
    delta_lon = lon2_rad - lon1_rad
    a = np.sin(delta_lat / 2) ** 2 + np.cos(lat1_rad) * np.cos(lat2_rad) * np.sin(delta_lon / 2) ** 2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))

    # Calcular la distancia
    distance = earth_radius * c

    return distance


# Calcular la latitud y longitud promedio
avg_lat = (df1['latitude'].mean() + df2['latitude'].mean()) / 2
avg_lon = (df1['longitude'].mean() + df2['longitude'].mean()) / 2

# Agregar columnas de distancia a Dataframes utilizando distancia geodésica
df1['distance_to_ref'] = df1.apply(lambda row: geodesic((row['latitude'], row['longitude']), (avg_lat, avg_lon)).m, axis=1)
df2['distance_to_ref'] = df2.apply(lambda row: geodesic((row['latitude'], row['longitude']), (avg_lat, avg_lon)).m, axis=1)

In [24]:
merged_df3 = df1.merge(df2, on='distance_to_ref', how='inner', sort=False)
merged_df3.head()

,business_id,name,address_x,city,state_x,postal_code,latitude_x,longitude_x,stars,review_count,...,state_y,relative_results,url,user_id,name_y,time,rating,text,pics,resp
0,OD6RYPrU2QTyTg6_4GYpbA,Brandon Pizzeria,140 N Parsons Ave,Brandon,FL,33510,27.939206,-82.286084,3.5,147,...,Open ⋅ Closes 9PM,None,https://www.google.com/maps/place//data=!4m2!3...,1.091736e+20,Jesse Nieves,1610802361016,5,The restaurant is open for dining and provides...,[{'url': ['https://lh5.googleusercontent.com/p...,{'text': 'Jesse thanks so much for your suppor...
1,OD6RYPrU2QTyTg6_4GYpbA,Brandon Pizzeria,140 N Parsons Ave,Brandon,FL,33510,27.939206,-82.286084,3.5,147,...,Open ⋅ Closes 9PM,None,https://www.google.com/maps/place//data=!4m2!3...,1.048419e+20,Brandon Rivera,1615592749399,5,Went here bc we wanted pizza and thought it wa...,[{'url': ['https://lh5.googleusercontent.com/p...,{'text': 'Brandon thanks so much for the great...
2,OD6RYPrU2QTyTg6_4GYpbA,Brandon Pizzeria,140 N Parsons Ave,Brandon,FL,33510,27.939206,-82.286084,3.5,147,...,Open ⋅ Closes 9PM,None,https://www.google.com/maps/place//data=!4m2!3...,1.088751e+20,Dirty McFergie,1618178402121,5,Such a variety of food and every item I have t...,None,{'text': 'Thank you for the wonderful review! ...
3,OD6RYPrU2QTyTg6_4GYpbA,Brandon Pizzeria,140 N Parsons Ave,Brandon,FL,33510,27.939206,-82.286084,3.5,147,...,Open ⋅ Closes 9PM,None,https://www.google.com/maps/place//data=!4m2!3...,1.154607e+20,Erik Chambers,1615426136118,5,"Food is fantastic, pizza had great flavor and ...",None,{'text': 'Thanks so much for the great review!...
4,OD6RYPrU2QTyTg6_4GYpbA,Brandon Pizzeria,140 N Parsons Ave,Brandon,FL,33510,27.939206,-82.286084,3.5,147,...,Open ⋅ Closes 9PM,None,https://www.google.com/maps/place//data=!4m2!3...,1.028419e+20,Benjamin Kent,1615943551381,5,What a fresh menu! Owners hand craft spicy che...,None,{'text': 'Ben thanks so much for the great rev...

In [47]:
print("Número de filas en filtered_result:", len(merged_df3))

Número de filas en filtered_result: 858

In [52]:
import geopandas as gpd
from shapely.geometry import Point
import pandas as pd

# Cargar los datasets
business_fl = pd.read_parquet('business_fl.parquet')
joined_restaurant_bars = pd.read_parquet('Joined_Restaurant_Bars_Florida_Google.parquet')

# Convertir dataframes a GeoDataFrames
business_fl_gdf = gpd.GeoDataFrame(business_fl, geometry=[Point(xy) for xy in zip(business_fl.longitude, business_fl.latitude)])
joined_restaurant_bars_gdf = gpd.GeoDataFrame(joined_restaurant_bars, geometry=[Point(xy) for xy in zip(joined_restaurant_bars.longitude, joined_restaurant_bars.latitude)])

# Establecer el sistema de referencia de coordenadas
business_fl_gdf.crs = 'EPSG:4326'
joined_restaurant_bars_gdf.crs = 'EPSG:4326'

# Unir espacialmente
result = gpd.sjoin(business_fl_gdf, joined_restaurant_bars_gdf, how='inner', op='intersects')

# Calcular la distancia entre los puntos
result['distance'] = result.apply(lambda row: row['geometry'].distance(Point(row['longitude_right'], row['latitude_right'])), axis=1)
filtered_result = result[result['distance'] <= 100]  # 1 km de distancia máxima

# Mostrar las primeras filas del dataset unido
print(filtered_result.head())

C:\Users\zimme\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py:3490: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
  if await self.run_code(code, result, async_=asy):

                 business_id              name       address_left     city  \
4556  OD6RYPrU2QTyTg6_4GYpbA  Brandon Pizzeria  140 N Parsons Ave  Brandon
4556  OD6RYPrU2QTyTg6_4GYpbA  Brandon Pizzeria  140 N Parsons Ave  Brandon
4556  OD6RYPrU2QTyTg6_4GYpbA  Brandon Pizzeria  140 N Parsons Ave  Brandon
4556  OD6RYPrU2QTyTg6_4GYpbA  Brandon Pizzeria  140 N Parsons Ave  Brandon
4556  OD6RYPrU2QTyTg6_4GYpbA  Brandon Pizzeria  140 N Parsons Ave  Brandon

     state_left  postal_code  latitude_left  longitude_left  stars  \
4556         FL        33510      27.939206      -82.286084    3.5
4556         FL        33510      27.939206      -82.286084    3.5
4556         FL        33510      27.939206      -82.286084    3.5
4556         FL        33510      27.939206      -82.286084    3.5
4556         FL        33510      27.939206      -82.286084    3.5

      review_count  ...  relative_results  \
4556           147  ...              None
4556           147  ...              None
4556           147  ...              None
4556           147  ...              None
4556           147  ...              None

                                                    url       user_id  \
4556  https://www.google.com/maps/place//data=!4m2!3...  1.101683e+20
4556  https://www.google.com/maps/place//data=!4m2!3...  1.179073e+20
4556  https://www.google.com/maps/place//data=!4m2!3...  1.141733e+20
4556  https://www.google.com/maps/place//data=!4m2!3...  1.010645e+20
4556  https://www.google.com/maps/place//data=!4m2!3...  1.035939e+20

               name_y           time  rating  \
4556   Mildred Medina  1611457364739       5
4556    Tonya Donahue  1619541042799       5
4556      Vivian Self  1612568525675       1
4556  Anthony Gembala  1623101175472       1
4556    Mary Sandoval  1616611381974       5

                                                   text  pics  \
4556  Got to work on their serving time but they sti...  None
4556                                   Excellent pizza!  None
4556                                    Not my favorite  None
4556                                               None  None
4556                                               None  None

                                                   resp distance
4556  {'text': 'Mildred, Thanks for the great review...      0.0
4556  {'text': 'Thanks for the great review Tonya!  ...      0.0
4556                                               None      0.0
4556                                               None      0.0
4556  {'text': 'Mary, thanks so much for the great r...      0.0

[5 rows x 42 columns]

In [53]:
print("Número de filas en filtered_result:", len(filtered_result))

Número de filas en filtered_result: 822

In [37]:
filtered_result.head()

,business_id,name,address_left,city,state_left,postal_code,latitude_left,longitude_left,stars,review_count,...,relative_results,url,user_id,name_y,time,rating,text,pics,resp,distance
4556,OD6RYPrU2QTyTg6_4GYpbA,Brandon Pizzeria,140 N Parsons Ave,Brandon,FL,33510,27.939206,-82.286084,3.5,147,...,None,https://www.google.com/maps/place//data=!4m2!3...,1.101683e+20,Mildred Medina,1611457364739,5,Got to work on their serving time but they sti...,None,"{'text': 'Mildred, Thanks for the great review...",0.0
4556,OD6RYPrU2QTyTg6_4GYpbA,Brandon Pizzeria,140 N Parsons Ave,Brandon,FL,33510,27.939206,-82.286084,3.5,147,...,None,https://www.google.com/maps/place//data=!4m2!3...,1.179073e+20,Tonya Donahue,1619541042799,5,Excellent pizza!,None,{'text': 'Thanks for the great review Tonya! ...,0.0
4556,OD6RYPrU2QTyTg6_4GYpbA,Brandon Pizzeria,140 N Parsons Ave,Brandon,FL,33510,27.939206,-82.286084,3.5,147,...,None,https://www.google.com/maps/place//data=!4m2!3...,1.141733e+20,Vivian Self,1612568525675,1,Not my favorite,None,None,0.0
4556,OD6RYPrU2QTyTg6_4GYpbA,Brandon Pizzeria,140 N Parsons Ave,Brandon,FL,33510,27.939206,-82.286084,3.5,147,...,None,https://www.google.com/maps/place//data=!4m2!3...,1.010645e+20,Anthony Gembala,1623101175472,1,None,None,None,0.0
4556,OD6RYPrU2QTyTg6_4GYpbA,Brandon Pizzeria,140 N Parsons Ave,Brandon,FL,33510,27.939206,-82.286084,3.5,147,...,None,https://www.google.com/maps/place//data=!4m2!3...,1.035939e+20,Mary Sandoval,1616611381974,5,None,None,"{'text': 'Mary, thanks so much for the great r...",0.0

In [39]:
print("Número de filas en la columna 'name':", filtered_result['name'].count())

Número de filas en la columna 'name': 822

In [2]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors

# Cargar los datasets
business_fl = pd.read_parquet('business_fl.parquet')
joined_restaurant_bars = pd.read_parquet('Joined_Restaurant_Bars_Florida_Google.parquet')

# Extraer las coordenadas
coords_business = business_fl[['latitude', 'longitude']].values
coords_restaurants = joined_restaurant_bars[['latitude', 'longitude']].values

# Configurar el modelo de Nearest Neighbors
nbrs = NearestNeighbors(n_neighbors=1, algorithm='ball_tree').fit(coords_restaurants)
distances, indices = nbrs.kneighbors(coords_business)

# Agregar los índices y distancias al dataframe de negocios
business_fl['nearest_restaurant_index'] = indices.flatten()
business_fl['distance_to_nearest'] = distances.flatten()

# Hacer el merge basado en los índices de los vecinos más cercanos
merged_df5 = business_fl.merge(joined_restaurant_bars, left_on='nearest_restaurant_index', right_index=True, suffixes=('_business', '_restaurant'))

# Mostrar las primeras filas del dataframe unido
print(merged_df5.head())
print("Número de filas en merged_df:", merged_df5.shape[0])

              business_id                  name      address_business  \
0  0bPLkL0QhhPO5kt1_EXmNQ  Zio's Italian Market         2575 E Bay Dr
1  cVBxfMC4lp3DnocjYA3FHQ     Paws The Cat Cafe      10588 109 Street
2  seKihQKpGGnCeLuELRQPSQ            Twin Peaks        6880 E 82nd St
3  L_TT0BFmFwORAMaA83K54A      Village Tap Room  838 Broad Ripple Ave
4  ppFCk9aQkM338Rgwpl2F5A                  Wawa      3604 Chestnut St

           city state_business  postal_code  latitude_business  \
0         Largo             FL        33771          27.916116
1      Edmonton             FL         <NA>          53.549633
2  Indianapolis             FL        46250          39.906295
3  Indianapolis             FL        46220          39.869911
4  Philadelphia             FL        19104          39.954573

   longitude_business  stars  review_count  ...     state_restaurant  \
0          -82.760461    4.5           100  ...  Closed ⋅ Opens 10AM
1         -113.508780    5.0            20  ...    Open ⋅ Closes 8PM
2          -86.047463    3.5           257  ...    Open ⋅ Closes 8PM
3          -86.143577    2.5            23  ...    Open ⋅ Closes 8PM
4          -75.194894    3.0            56  ...   Permanently closed

                                    relative_results  \
0  [0x88c2fa7abc195651:0x81f6a81d2c828584, 0x88c2...
1                                               None
2                                               None
3                                               None
4  [0x88e4ff6d99b69c5b:0x9692f5134ee244c7, 0x88e4...

                                                 url       user_id  \
0  https://www.google.com/maps/place//data=!4m2!3...  1.094284e+20
1  https://www.google.com/maps/place//data=!4m2!3...  1.070861e+20
2  https://www.google.com/maps/place//data=!4m2!3...  1.070861e+20
3  https://www.google.com/maps/place//data=!4m2!3...  1.070861e+20
4  https://www.google.com/maps/place//data=!4m2!3...  1.166253e+20

           name_y           time rating  \
0      Juan Avila  1619993512409      4
1  Jennie Adelman  1626124978684      5
2  Jennie Adelman  1626124978684      5
3  Jennie Adelman  1626124978684      5
4         Jay Bee  1486310391596      5

                                                text  \
0                                          It was ok
1  Very nice, clean restaurant. Quiet today but m...
2  Very nice, clean restaurant. Quiet today but m...
3  Very nice, clean restaurant. Quiet today but m...
4  From the service to the food...Awesome experie...

                                                pics  resp
0  [{'url': ['https://lh5.googleusercontent.com/p...  None
1                                               None  None
2                                               None  None
3                                               None  None
4  [{'url': ['https://lh5.googleusercontent.com/p...  None

[5 rows x 41 columns]
Número de filas en merged_df: 11997

In [64]:
merged_df5.head(10)

,business_id,name,address_business,city,state_business,postal_code,latitude_business,longitude_business,stars,review_count,is_open,attributes,categories,hours_business,rounded_latitude,rounded_longitude,normalized_name,nearest_restaurant_index,distance_to_nearest,name_x,address_restaurant,gmap_id,description,latitude_restaurant,longitude_restaurant,category,avg_rating,num_of_reviews,price,hours_restaurant,MISC,state_restaurant,relative_results,url,user_id,name_y,time,rating,text,pics,resp
0,0bPLkL0QhhPO5kt1_EXmNQ,Zio's Italian Market,2575 E Bay Dr,Largo,FL,33771,27.916116,-82.760461,4.5,100,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Food, Delis, Italian, Bakeries, Restaurants","{'Friday': '10:0-20:0', 'Monday': '10:0-18:0',...",27.92,-82.76,"Local en (27.7121935, -82.2979132)",24401,0.003153,Knockn Boots Saloon,"Knockn Boots Saloon, 201 Keene Rd Suite 3, Lar...",0x88c2fbf2a7d494a1:0x459477037ba946de,None,27.918947,-82.761847,[Bar],4.6,31,None,"[[Thursday, 10AM–12AM], [Friday, 10AM–12AM], [...","{'Accessibility': None, 'Activities': None, 'A...",Closed ⋅ Opens 10AM,"[0x88c2fa7abc195651:0x81f6a81d2c828584, 0x88c2...",https://www.google.com/maps/place//data=!4m2!3...,1.094284e+20,Juan Avila,1619993512409,4,It was ok,[{'url': ['https://lh5.googleusercontent.com/p...,None
1,cVBxfMC4lp3DnocjYA3FHQ,Paws The Cat Cafe,10588 109 Street,Edmonton,FL,<NA>,53.549633,-113.508780,5.0,20,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Coffee & tea, Cafes, Pets, Restaurants, Pet ad...","{'Friday': '10:0-20:0', 'Monday': '0:0-0:0', '...",53.55,-113.51,"Local en (27.772925866666668, -82.67718393333334)",13204,34.720632,Royal Mexican Grill,"Royal Mexican Grill, 13951 S Alabama St, Jay, ...",0x88905f5c53bd0b7d:0x8e6c65ab8289a406,None,30.944592,-87.154760,[Restaurant],4.4,38,None,"[[Wednesday, 11AM–8PM], [Thursday, 11AM–8PM], ...",{'Accessibility': ['Wheelchair accessible entr...,Open ⋅ Closes 8PM,None,https://www.google.com/maps/place//data=!4m2!3...,1.070861e+20,Jennie Adelman,1626124978684,5,"Very nice, clean restaurant. Quiet today but m...",None,None
2,seKihQKpGGnCeLuELRQPSQ,Twin Peaks,6880 E 82nd St,Indianapolis,FL,46250,39.906295,-86.047463,3.5,257,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Sports bars, American (new), American (traditi...","{'Friday': '11:0-19:0', 'Monday': '0:0-0:0', '...",39.91,-86.05,"Local en (27.7679350194, -82.3935427381)",13204,9.029852,Royal Mexican Grill,"Royal Mexican Grill, 13951 S Alabama St, Jay, ...",0x88905f5c53bd0b7d:0x8e6c65ab8289a406,None,30.944592,-87.154760,[Restaurant],4.4,38,None,"[[Wednesday, 11AM–8PM], [Thursday, 11AM–8PM], ...",{'Accessibility': ['Wheelchair accessible entr...,Open ⋅ Closes 8PM,None,https://www.google.com/maps/place//data=!4m2!3...,1.070861e+20,Jennie Adelman,1626124978684,5,"Very nice, clean restaurant. Quiet today but m...",None,None
3,L_TT0BFmFwORAMaA83K54A,Village Tap Room,838 Broad Ripple Ave,Indianapolis,FL,46220,39.869911,-86.143577,2.5,23,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Gastropubs, Cocktail bars, Beer bar, Bars, Res...",None,39.87,-86.14,"Local en (27.782413, -82.781687)",13204,8.982417,Royal Mexican Grill,"Royal Mexican Grill, 13951 S Alabama St, Jay, ...",0x88905f5c53bd0b7d:0x8e6c65ab8289a406,None,30.944592,-87.154760,[Restaurant],4.4,38,None,"[[Wednesday, 11AM–8PM], [Thursday, 11AM–8PM], ...",{'Accessibility': ['Wheelchair accessible entr...,Open ⋅ Closes 8PM,None,https://www.google.com/maps/place//data=!4m2!3...,1.070861e+20,Jennie Adelman,1626124978684,5,"Very nice, clean restaurant. Quiet today but m...",None,None
4,ppFCk9aQkM338Rgwpl2F5A,Wawa,3604 Chestnut St,Philadelphia,FL,19104,39.954573,-75.194894,3.0,56,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Restaurants, Automotive, Delis, Gas stations, ...","{'Friday': '0:0-0:0', 'Monday': '0:0-0:0', 'Sa...",39.95,-75.19,"Local en (27.7937428, -82.6465296)",7697,11.199968,Lucas On Centre,"Lucas On Centre, 614 Centre St, Fernandina Bea...",0x88e4fee538ce8753:0x9cfef5f1931c840d,Charming eatery with a cosmopolitan interior t...,30.670693,-81.459783,"[Gastropub, Restaurant]",4.5,58,$$,"[[Saturday, 5:30–9:30PM], [Sunday, 5:30–9PM], ...",{'Accessibility': ['Wheelchair accessible elev...,Permanently closed,"[0x88e4ff6d99b69c5b:0x9692f5134ee244c7, 0x88e4...",https://www.google.com/maps/place//data=!4m2!3...,1.166253e+20,Jay Bee,1486310391596,5,From the service to the food...Awesome experie...,[{'url': ['https://lh5.googleusercontent.com/p...,None
5,kk_oEw1j3xQ-cJaAII8A0Q,Giant Food Store,1760 Dekalb Pike,Blue Bell,FL,19422,40.149065,-75.306028,3.0,29,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Grocery, Food","{'Friday': '6:0-0:0', 'Monday': '6:0-0:0', 'Sa...",40.15,-75.31,"Local en (27.830447300000003, -82.72859890000001)",7697,11.300807,Lucas On Centre,"Lucas On Centre, 614 Centre St, Fernandina Bea...",0x88e4fee538ce8753:0x9cfef5f1931c840d,Charming eatery with a cosmopolitan interior t...,30.670693,-81.459783,"[Gastropub, Restaurant]",4.5,58,$$,"[[Saturday, 5:30–9:30PM], [Sunday, 5:30–9PM], ...",{'Accessibility': ['Wheelchair accessible elev...,Permanently closed,"[0x88e4ff6d99b69c5b:0x9692f5134ee244c7, 0x88e4...",https://www.google.com/maps/place//data=!4m2!3...,1.166253e+20,Jay Bee,1486310391596,5,From the service to the food...Awesome experie...,[{'url': ['https://lh5.googleusercontent.com/p...,None
6,qFX8IdomeBVhDPCSyz2aRg,Nashville Delivers,6591 Bluff Rd,Brentwood,FL,37027,36.002397,-86.702381,3.5,7,1,None,"Couriers & delivery services, Local services, ...",None,36.00,-86.70,"Local en (27.827789, -82.6593784)",13204,5.077996,Royal Mexican Grill,"Royal Mexican Grill, 13951 S Alabama St, Jay, ...",0x88905f5c53bd0b7d:0x8e6c65ab8289a406,None,30.944592,-87.154760,[Restaurant],4.4,38,None,"[[Wednesday, 11AM–8PM], [Thursday, 11AM–8PM], ...",{'Accessibility': ['Wheelchair accessible entr...,Open ⋅ Closes 8PM,None,https://www.google.com/maps/place//data=!4m2!3...,1.070861e+20,Jennie Adelman,1626124978684,5,"Very nice, clean restaurant. Quiet today but m...",None,None
7,FRYkg_JvsWU9xIXZsEZcVA,Altamura,2127 Prytania St,New Orleans,FL,70115,29.933388,-90.079498,3.5,27,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Cocktail bars, Italian, Nightlife, Seafood, Ba...","{'Friday': '17:0-23:0', 'Monday': '17:0-22:0',...",29.93,-90.08,"Local en (27.840020720000002, -82.71833154000001)",33274,2.707678,Shell,"Shell, 12388 Sorrento Rd, Pensacola, FL 32507",0x8890a51536889d65:0xc87ccec0c06210c7,None,30.341442,-87.402744,"[Gas station, Alternative fuel station, ATM, C...",3.4,35,$$,None,{'Accessibility': ['Wheelchair accessible entr...,Open now,"[0x8890af7e058ada2b:0xd9367f771d4e75ce, 0x8890...",https://www.google.com/maps/place//data=!4m2!3...,1.144808e+20,Dee Johnson,1502325153579,5,"PAFCU ATM, fantastic Chinese food made fresh a...",None,None
8,0vCsslN-TYnDeOSNT4rIfg,Whole Foods Market,14598 Clay Terrace Blvd,Carmel,FL,46032,39.999084,-86.131076,3.5,44,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Food, Organic stores, Specialty food, Health m...","{'Friday': '8:0-21:0', 'Monday': '0:0-0:0', 'S...",40.00,-86.13,"Local en (27.847392149999997, -82.70058430335)",13204,9.112176,Royal Mexican Grill,"Royal Mexican Grill, 13951 S Alabama St, Jay, ...",0x88905f5c53bd0b7d:0x8e6c65ab8289a406,None,30.944592,-87.154760,[Restaurant],4.4,38,None,"[[Wednesday, 11AM–8PM], [Thursday, 11AM–8PM], ...",{'Accessibility': ['Wheelchair accessible entr...,Open ⋅ Closes 8PM,None,https://www.google.com/maps/place//data=!4m2!3...,1.070861e+20,Jennie Adelman,1626124978684,5,"Very nice, clean restaurant. Quiet today but m...",None,None
9,7Du9oW73YcYFmXdtU5aiSg,Kinjo's Japanese Restaurant,2875 Tyrone Blvd N,Saint Petersburg,FL,33710,27.797263,-82.733913,3.5,17,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Japanese, Sushi bars, Restaurants","{'Friday': '12:0-1:0', 'Monday': '12:0-22:0', ...",27.80,-82.73,"Local en (27.892573497366666, -82.73008774403333)",11257,0.002467,COBBSTERS KITCHEN & BAR,"COBBSTERS KITCHEN & BAR, St. Petersburg, FL 33710",0x88c2e332bc6d9555:0x4c5649c8376446db,None,27.797176,-82.736379,"[Restaurant, Bar]",4.2,18,None,"[[Saturday, 10AM–9PM], [Sunday, 11AM–7PM], [Mo...",{'Accessibility': ['Wheelchair accessible entr...,Open ⋅ Closes 9PM,"[0x88c2e3326a3c3b1f:0x22ae750e5d692832, 0x88c2...",https://www.google.com/maps/place//data=!4m2!3...,1.058656e+20,Patrick McAuliffe,1602425519763,5,Joy at the bar is truly a lovely person and th...,None,None

In [59]:
print(merged_df5.columns)

Index(['business_id', 'name', 'address_business', 'city', 'state_business',
       'postal_code', 'latitude_business', 'longitude_business', 'stars',
       'review_count', 'is_open', 'attributes', 'categories', 'hours_business',
       'rounded_latitude', 'rounded_longitude', 'normalized_name',
       'nearest_restaurant_index', 'distance_to_nearest', 'name_x',
       'address_restaurant', 'gmap_id', 'description', 'latitude_restaurant',
       'longitude_restaurant', 'category', 'avg_rating', 'num_of_reviews',
       'price', 'hours_restaurant', 'MISC', 'state_restaurant',
       'relative_results', 'url', 'user_id', 'name_y', 'time', 'rating',
       'text', 'pics', 'resp'],
      dtype='object')

In [61]:
print(merged_df5['category'])

0                                                    [Bar]
1                                             [Restaurant]
2                                             [Restaurant]
3                                             [Restaurant]
4                                  [Gastropub, Restaurant]
                               ...
11992                              [Gastropub, Restaurant]
11993                                         [Restaurant]
11994                                         [Restaurant]
11995    [Gas station, Alternative fuel station, ATM, C...
11996                                                [Bar]
Name: category, Length: 11997, dtype: object

In [67]:
print(merged_df5[['category', 'name', 'address_business', 'city']])

                                                category  \
0                                                  [Bar]
1                                           [Restaurant]
2                                           [Restaurant]
3                                           [Restaurant]
4                                [Gastropub, Restaurant]
...                                                  ...
11992                            [Gastropub, Restaurant]
11993                                       [Restaurant]
11994                                       [Restaurant]
11995  [Gas station, Alternative fuel station, ATM, C...
11996                                              [Bar]

                                name           address_business  \
0               Zio's Italian Market              2575 E Bay Dr
1                  Paws The Cat Cafe           10588 109 Street
2                         Twin Peaks             6880 E 82nd St
3                   Village Tap Room       838 Broad Ripple Ave
4                               Wawa           3604 Chestnut St
...                              ...                        ...
11992                  King of Tarts  1414 E Old York Rd, Ste E
11993              El Cap Restaurant              3500 4th St N
11994                 Plantation Pub       8321 Sawyer Brown Rd
11995             Don Cruz Snowballs         4213 Williams Blvd
11996  Colony Grill - St. Petersburg            670 Central Ave

                 city
0               Largo
1            Edmonton
2        Indianapolis
3        Indianapolis
4        Philadelphia
...               ...
11992      Warminster
11993  St. Petersburg
11994        Bellevue
11995          Kenner
11996  St. Petersburg

[11997 rows x 4 columns]

In [75]:
print(merged_df5['distance_to_nearest'])

0         0.003153
1        34.720632
2         9.029852
3         8.982417
4        11.199968
           ...
11992    11.483512
11993     0.008484
11994     5.130329
11995     2.852440
11996     0.000120
Name: distance_to_nearest, Length: 11997, dtype: float64

In [65]:
null_count = merged_df5['category'].isna().sum()
print(null_count)

0

In [68]:
null_count = merged_df5['gmap_id'].isna().sum()
print(null_count)

0

In [3]:
total_null_count = merged_df5.isna().sum()
print(total_null_count)

business_id                     0
name                            0
address_business                0
city                            0
state_business                  0
postal_code                   538
latitude_business               0
longitude_business              0
stars                           0
review_count                    0
is_open                         0
attributes                    150
categories                      0
hours_business               1703
rounded_latitude                0
rounded_longitude               0
normalized_name             11675
nearest_restaurant_index        0
distance_to_nearest             0
name_x                          0
address_restaurant              2
gmap_id                         0
description                  7289
latitude_restaurant             0
longitude_restaurant            0
category                        0
avg_rating                      0
num_of_reviews                  0
price                        4647
hours_restaurant             1928
MISC                           24
state_restaurant              146
relative_results             4035
url                             0
user_id                         0
name_y                          0
time                            0
rating                          0
text                          367
pics                         7760
resp                        10918
dtype: int64

In [5]:
merged_df5.isnull().values.sum()

51182

In [7]:
import pandas as pd

# Assuming you have a DataFrame named 'merged_df5'

# Step 1: Check for duplicate rows or columns
if merged_df5.duplicated().sum() > 0:
    print("Warning: Duplicate rows or columns detected. Null value count might be inflated.")

# Step 2: Identify null values using 'isna()'
null_values = merged_df5.isna()

# Step 3: Count null values in each row and column
null_counts_per_row = null_values.sum(axis=1)
null_counts_per_col = null_values.sum(axis=0)

# Step 4: Calculate the total null value count
total_null_count = null_counts_per_row.sum()

# Print the total null value count
print("Total number of null values:", total_null_count)

# Optional: Display null counts per row and column
print("\nNull counts per row:")
print(null_counts_per_row)

print("\nNull counts per column:")
print(null_counts_per_col)

TypeError: unhashable type: 'dict'

In [4]:
num_rows, num_cols = merged_df5.shape

# Print the row and column counts
print("Number of rows:", num_rows)
print("Number of columns:", num_cols)

Number of rows: 11997
Number of columns: 41

In [72]:
unique_business_id_count = merged_df5['business_id'].nunique()
print(unique_business_id_count)

11997

In [3]:
merged_df5['category'].value_counts()

category
[Restaurant]                                                                                                      4146
[Gastropub, Restaurant]                                                                                           3753
[Gas station, Alternative fuel station, ATM, Convenience store, Electric vehicle charging station, Restaurant]    1781
[Bar]                                                                                                              880
[Sports bar, Bar, Irish pub]                                                                                        20
                                                                                                                  ...
[Sports bar, Restaurant]                                                                                             1
[Mexican restaurant, Fast food restaurant, Restaurant]                                                               1
[Sandwich shop, Caterer, Fast food restaurant, Takeout Restaurant, Restaurant]                                       1
[Grocery store, Fresh food market, Meat products, Restaurant]                                                        1
[Bar, Event venue, Irish pub, Irish restaurant, Karaoke, Live music venue, Pub, Sports bar]                          1
Name: count, Length: 337, dtype: int64

In [3]:
merged_df5.to_parquet('Joined Business y Restaurant_Bar Florida.parquet')

In [4]:
import pandas as pd
import pyarrow as pa

# Read JSON data into a DataFrame
df = pd.read_json('review.json')

# Convert DataFrame to Arrow Table
table = pa.Table.from_pandas(df)

# Write Arrow Table to Parquet file
table.write_to_parquet('review.parquet')

MemoryError:

In [14]:

sweetgreen_rows = merged_df5[merged_df5['name'].str.contains('Sweetgreen', case=False)]


# Count the number of rows in the filtered DataFrame (number of occurrences)
sweetgreen_count = sweetgreen_rows.shape[0]

# Print the count
print(sweetgreen_count)

11997

In [13]:
merged_df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11997 entries, 0 to 11996
Data columns (total 41 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   business_id               11997 non-null  object
 1   name                      11997 non-null  object
 2   address_business          11997 non-null  object
 3   city                      11997 non-null  object
 4   state_business            11997 non-null  object
 5   postal_code               11459 non-null  Int64
 6   latitude_business         11997 non-null  float64
 7   longitude_business        11997 non-null  float64
 8   stars                     11997 non-null  float64
 9   review_count              11997 non-null  int64
 10  is_open                   11997 non-null  int64
 11  attributes                11847 non-null  object
 12  categories                11997 non-null  object
 13  hours_business            10294 non-null  object
 14  rounded_latitude          11997 non-null  float64
 15  rounded_longitude         11997 non-null  float64
 16  normalized_name           322 non-null    object
 17  nearest_restaurant_index  11997 non-null  int64
 18  distance_to_nearest       11997 non-null  float64
 19  name_x                    11997 non-null  object
 20  address_restaurant        11995 non-null  object
 21  gmap_id                   11997 non-null  object
 22  description               4708 non-null   object
 23  latitude_restaurant       11997 non-null  float64
 24  longitude_restaurant      11997 non-null  float64
 25  category                  11997 non-null  object
 26  avg_rating                11997 non-null  float64
 27  num_of_reviews            11997 non-null  int64
 28  price                     7350 non-null   object
 29  hours_restaurant          10069 non-null  object
 30  MISC                      11973 non-null  object
 31  state_restaurant          11851 non-null  object
 32  relative_results          7962 non-null   object
 33  url                       11997 non-null  object
 34  user_id                   11997 non-null  float64
 35  name_y                    11997 non-null  object
 36  time                      11997 non-null  int64
 37  rating                    11997 non-null  int64
 38  text                      11630 non-null  object
 39  pics                      4237 non-null   object
 40  resp                      1079 non-null   object
dtypes: Int64(1), float64(10), int64(6), object(24)
memory usage: 3.8+ MB

In [9]:
merged_df5['name'].value_counts

name
Sweetgreen    11997
Name: count, dtype: int64